[package]
name = "danielUnTask/task"
description = "Lightweight task scheduler with coroutine pooling."
version = "0.1.0"
License = "MIT"
authors = ["Daniel Olvera"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml", "README.md", "selene.toml", "sourcemap.json", "LICENSE", "default.project.json", ".gitignore"]